application: doxcart
version: 1
runtime: go
api_version: go1

handlers:
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: build/js
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^js/.*$
- ^(.*/)?node_modules/.*$
- ^(.*/)?gulpfile\.js$
- ^(.*/)?package\.json$
- ^(.*/)?README\.md$
- ^(.*/)?.*\.sublime-project$
- ^(.*/)?.*\.sublime-workspace$
